version: '3'

volumes:
  credit_approval_system_postgres_data: {}
  credit_approval_system_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: credit_approval_system_django
    container_name: credit_approval_system_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
      - ./.env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: credit_approval_system_postgres
    container_name: credit_approval_system_postgres
    volumes:
      - credit_approval_system_postgres_data:/var/lib/postgresql/data
      - credit_approval_system_postgres_data_backups:/backups
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: credit_approval_system_redis
    ports:
      - '6379:6379'

  celeryworker:
    <<: *django
    image: credit_approval_system_celeryworker
    container_name: credit_approval_system_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: credit_approval_system_celerybeat
    container_name: credit_approval_system_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: credit_approval_system_flower
    container_name: credit_approval_system_flower
    ports:
      - '5555:5555'
    command: /start-flower