# Generated by Django 5.0.2 on 2024-03-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("monthly_income", models.FloatField()),
                ("approved_limit", models.FloatField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_amount", models.FloatField()),
                ("interest_rate", models.FloatField()),
                ("tenure", models.IntegerField()),
                ("monthly_repayment", models.FloatField()),
                ("emis_paid_on_time", models.IntegerField()),
                ("end_date", models.DateField()),
                ("date_of_approval", models.DateField()),
                ("loan_approved", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
            ],
        ),
    ]
